### ISSUE TITLE
Fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by gmatesunny** [jgaa/restc-cpp#40]
I followed this: https://github.com/jgaa/restc-cpp/wiki/Building-under-Linux

But it fails to build with error:

 /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by gmatesunny** [comment]
roshan@bolt:~/SGXcompliment/restc-cpp/dbuild$ cmake ..
-- EXTERNAL_RAPIDJSON_INCLUDE_DIR: /home/roshan/SGXcompliment/restc-cpp/dbuild/external-projects/installed/include/rapidjson
-- Using /usr/bin/c++
-- Using C++ 14
-- Boost version: 1.58.0
-- Found the following Boost libraries:

**Comment by gmatesunny** [comment]
cmake_minimum_required(VERSION 3.0)
project (restc-cpp VERSION 0.9.0)

SET( CMAKE_CXX_FLAGS -std=c++14)
if (NOT DEFINED INSTALL_RAPIDJSON_HEADERS)

fixes it.
